spring:
  application:
    name: company-service
  config:
    import: optional:configserver:http://localhost:8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh