services:
  postgres:
    image: postgres:16-alpine
    container_name: lab2-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  config-server:
    build:
      context: ./config-server
      dockerfile: Dockerfile
    container_name: lab2-config-server
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: native
      SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS: /config-repo
    depends_on:
      - postgres
    volumes:
      - ./config-repo:/config-repo:ro

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: lab2-user-service
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8080
    depends_on:
      - config-server
      - postgres

  company-service:
    build:
      context: ./company-service
      dockerfile: Dockerfile
    container_name: lab2-company-service
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8080
    depends_on:
      - config-server
      - postgres

volumes:
  pgdata:


