spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://localhost:8080

  profiles:
    #active: test
    active: default

---
spring:
  config:
    activate:
      on-profile: docker
    import: optional:configserver:http://config-server:8080
  application:
    name: user-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh